# Pandas : Data frames

In [4]:
import pandas as pd

In [5]:
data_csv = pd.read_csv("data/course.csv")
data_csv.head()

,✅,COURS,CHAPITRE,IMPORTANCE
0,FALSE,Algèbre linéaire,Vecteurs et espaces vectoriels,Accessoire
1,FALSE,Algèbre linéaire,Matrices d'applications linéaires,Accessoire
2,FALSE,Algèbre linéaire,Changement de système de coordonnées,Accessoire
3,FALSE,Statistiques et probabilités,Séries statistiques à caractère qualitatif,Indispensable
4,FALSE,Statistiques et probabilités,Représentation et comparaison de données quant...,Indispensable

In [8]:
data_excel = pd.read_excel("data/course.xlsx")
data_excel.tail(3)

,✅,COURS,CHAPITRE,IMPORTANCE
140,False,GitHub,Livrable final : Docker-compose (optionnel mai...,Bonus
141,False,GitHub,Livrable final : Capture d'écran du dashboard ...,Indispensable
142,NaN,NaN,0,NaN

In [9]:
data_csv.dtypes

✅             str
COURS         str
CHAPITRE      str
IMPORTANCE    str
dtype: object

### Convertir en array NumPy

In [27]:
data_array = data_csv.values
data_array[:5,:]

array([['FALSE', 'Algèbre linéaire', 'Vecteurs et espaces vectoriels',
        'Accessoire'],
       ['FALSE', 'Algèbre linéaire', "Matrices d'applications linéaires",
        'Accessoire'],
       ['FALSE', 'Algèbre linéaire',
        'Changement de système de coordonnées', 'Accessoire'],
       ['FALSE', 'Statistiques et probabilités',
        'Séries statistiques à caractère qualitatif', 'Indispensable'],
       ['FALSE', 'Statistiques et probabilités',
        'Représentation et comparaison de données quantitatives',
        'Indispensable']], dtype=object)